### ISSUE TITLE
Rocket Chip Updates

### ISSUE THREAD

**Issue by aroelke** [IBM/chiffre#12]
This needs to be updated for the latest version of rocket-chip.  The `TLBundle*` classes no longer have `error` IO fields.

I applied a quick fix to that, but then I came across a Scala runtime error when trying to build the emulator.  The error is a `java.lang.reflect.InvocationTargetException` caused by:
```
java.lang.IllegalAccessError: tried to access field freechips.rocketchip.tile.RocketTileModuleImp.reflPoly$Cache4 from class freechips.rocketchip.tile.HasLazyRoCCModule$class
      at freechips.rocketchip.tile.HasLazyRoCCModule$class.reflMethod$Method4(LazyRoCC.scala:91)
```

**Comment by seldridge** [comment]
The fix you mentions makes sense. I'm seeing the same error that you're seeing now.

That appears to be something actually wrong with Rocket as it's failing the `RoccExampleConfig`. I can dig into it, but once it starts to run into problems with Diplomacy (what this looks like) I get somewhat lost.

**Comment by seldridge** [comment]
I went ahead and filed an issue on Rocket Chip here: https://github.com/freechipsproject/rocket-chip/issues/1515

**Comment by seldridge** [comment]
As far as I can tell, this appears to be a Rocket issues. I'm playing around trying to see if I can figure out a fix there. Otherwise, you'll have to use a version of Rocket that is before this issue showed up.

The offending commit appears to be https://github.com/freechipsproject/rocket-chip/commit/c563c9ce83af70dfbd019aa1701d71b4ac60e700. However, it's not intuitive why this is breaking it.

I think that anything before that PR got merged should be fine.

I'm closing this, but feel free to re-open if you find that this _is_ an issue with `LeChiffre`.

**Comment by aroelke** [comment]
Thanks, moving to the commit before that got it to work.

**Comment by seldridge** [comment]
This should be resolved with: https://github.com/freechipsproject/rocket-chip/commit/c07ae80590416043149e0e3ecb6f9217d074f8be
